home/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views


urlpatterns = [
    path('', views.home, name='home'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from django.conf import settings
from django.conf.urls.static import static

from users.views import login

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    # path('accounts/', include('accounts.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),

    # users
    path('', include('users.urls')),
    # home
    path('home', include('home.urls')),
    # academic
    path('academic/', include('academic.urls')),
    #programs
    path('programs/', include('programs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

programs/urls.py
from django.urls import path
from django.conf.urls import url, include

from .views import ProgramList, ProgramCreation, ProgramUpdate, ProgramDetail, SubProgramList, SubProgramList, SubprogramCreation, SubProgramUpdate, SubProgramDetail, SubProgramTaskDetail, SubProgramTaskAdd, TaskAdvanceDetail, TaskAdvanceAdd, SubProgramTaskList

urlpatterns = [
    path('program_list', ProgramList.as_view(), name='program_list'),
    path('program_add', ProgramCreation.as_view(), name='program_add'),
    path('program_edit/<int:pk>', ProgramUpdate.as_view(), name='program_edit'),
    path('program_detail/<int:pk>', ProgramDetail.as_view(), name='program_detail'),

    path('subprogram_by_program_list/<int:pk>', SubProgramList.as_view(), name='subprogram_by_program'),
    path('sub_program_list', SubProgramList.as_view(), name='sub_program_list'),
    path('subprogram_add/<int:program>', SubprogramCreation.as_view(), name='subprogram_add'),
    path('subprogram_update/<int:pk>', SubProgramUpdate.as_view(), name='subprogram_update'),
    path('subprogram_detail/<int:pk>', SubProgramDetail.as_view(), name='subprogram_detail'),

    path('subprogramtask_list', SubProgramTaskList.as_view(), name='subprogramtask_list'),
    path('subprogramtask_detail/<int:pk>', SubProgramTaskDetail.as_view(), name='subprogramtask_detail'),
    path('subprogramtask_add/<int:subprogram>', SubProgramTaskAdd.as_view(), name='subprogramtask_add'),

    path('taskadvance_detail/download/<path:document_path>', TaskAdvanceDetail.download_item, name='task_advance_download'),
    path('taskadvance_add/<int:task>', TaskAdvanceAdd.as_view(), name='task_advance_add'),
]

programs/models.py
from django.db import models

# Create your models here.
class Program(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500, blank=True, default='')
    start_date = models.DateField(auto_now=False, auto_now_add=False)
    end_date = models.DateField(auto_now=False, auto_now_add=False)
    acumulate_percentage = 0

class SubProgram(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500, blank=True, default='')
    program = models.ForeignKey(Program, on_delete=models.CASCADE)
    start_date = models.DateField(auto_now=False, auto_now_add=False)
    end_date = models.DateField(auto_now=False, auto_now_add=False)
    acumulate_percentage = 0

class SubProgramTask(models.Model):
    name = models.CharField(max_length=200)
    commentary = models.CharField(max_length=500, blank=True, default='')
    sub_program = models.ForeignKey(SubProgram, on_delete=models.CASCADE)
    acumulate_percentage = 0

class TaskAdvance(models.Model):
    commentary = models.TextField(max_length=1024*2)
    advance_file = models.FileField("file", upload_to="task_documents", max_length=100)
    percentage = models.IntegerField()
    completed = models.BooleanField(default=False, blank=True)
    task = models.ForeignKey(SubProgramTask, on_delete=models.CASCADE)
    upload_date = models.DateField(auto_now=True, blank=True)

programs/views.py
import os 
import zipfile

from django.conf import settings
from django.urls import reverse_lazy
from django.http import HttpResponse, FileResponse
from django.shortcuts import render
from django.utils.text import slugify
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Program, SubProgram, SubProgramTask, TaskAdvance

LOGIN_URL = '/login'

class ProgramList(LoginRequiredMixin, ListView):
    model = Program
    template_name= "programs/program/program_list.html"
    paginate_by = 10
    login_url = LOGIN_URL

class ProgramCreation(LoginRequiredMixin, CreateView):
    model = Program
    template_name = "programs/program/program_add.html"
    login_url = LOGIN_URL
    fields = ['name', 'description', 'start_date', 'end_date']
    success_url = reverse_lazy('program_list')

class ProgramUpdate(LoginRequiredMixin, UpdateView):
    model = Program
    template_name = "programs/program/program_update.html"
    login_url = LOGIN_URL
    fields = ['name', 'description', 'start_date', 'end_date']
    success_url = reverse_lazy('program_list')

class ProgramDetail(LoginRequiredMixin, DetailView):
    model = Program
    template_name = "programs/program/program_detail.html"
    login_url = LOGIN_URL

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['subprograms'] = SubProgram.objects.filter(program=kwargs['object'])
        for s in data['subprograms']:
            tasks = SubProgramTask.objects.filter(sub_program=s)
            for t in tasks:
                advances = TaskAdvance.objects.filter(task=t)
                acum = sum(advance.percentage for advance in advances)
            try:
                s.acumulate_percentage = int(acum / len(tasks))
            except Exception:
                s.acumulate_percentage = 0
        return data

class SubProgramList(LoginRequiredMixin, ListView):
    model = SubProgram
    template_name = "programs/subprogram/subprograms_list.html"
    paginate_by = 10
    login_url = LOGIN_URL

class SubprogramCreation(LoginRequiredMixin, CreateView):
    model = SubProgram
    template_name = "programs/subprogram/subprogram_add.html"
    fields = ['name', 'description', 'start_date', 'end_date']
    login_url = LOGIN_URL

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['program'] = Program.objects.get(pk=self.kwargs['program'])
        return data
    
    def form_valid(self, form):
        form.instance.program = Program.objects.get(pk=self.kwargs['program'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('program_detail', kwargs={'pk': self.kwargs["program"]})

class SubProgramUpdate(LoginRequiredMixin, UpdateView):
    model = SubProgram
    template_name = "programs/subprogram/subprogram_update.html"
    fields = ['name', 'description', 'start_date', 'end_date']
    login_url = LOGIN_URL
    success_url = reverse_lazy('sub_program_list')


class SubProgramDetail(LoginRequiredMixin, DetailView):
    model = SubProgram
    template_name = "programs/subprogram/subprogram_detail.html"
    login_url = LOGIN_URL

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['task'] = SubProgramTask.objects.filter(sub_program=kwargs['object'])
        for t in data['task']:
            advances = TaskAdvance.objects.filter(task=t)
            t.acumulate_percentage = sum(advance.percentage for advance in advances)
        return data

class SubProgramTaskList(LoginRequiredMixin, ListView):
    model = SubProgramTask
    template_name = "programs/task/task_list.html"
    paginate_by = 10
    login_url = LOGIN_URL

class SubProgramTaskDetail(LoginRequiredMixin, DetailView):
    model = SubProgramTask
    template_name = "programs/task/task_detail.html"
    login_url = LOGIN_URL

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['advances'] = TaskAdvance.objects.filter(task=kwargs['object']).order_by('id')
        return data

class SubProgramTaskAdd(LoginRequiredMixin, CreateView):
    model = SubProgramTask
    template_name = "programs/task/task_add.html"
    login_url = LOGIN_URL
    fields = ['name', 'commentary']
    
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['subprogram'] = SubProgram.objects.get(pk=self.kwargs['subprogram'])
        return data

    def form_valid(self, form):
        form.instance.sub_program = SubProgram.objects.get(pk=self.kwargs['subprogram'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('subprogram_detail', kwargs={'pk': self.kwargs["subprogram"]})

class TaskAdvanceDetail(LoginRequiredMixin, DetailView):
    model = TaskAdvance
    template_name = "programs/advance/advance_detail.html"
    login_url = LOGIN_URL

    def download_item(request, document_path):
        file_name, file_extension = os.path.splitext(document_path)
        filepath = os.path.join(settings.MEDIA_ROOT)
        file_extension = file_extension[1:] # removes dot
        
        with open(filepath+'/'+document_path, 'rb') as file:
            response = HttpResponse(file, content_type='file/%s' % file_extension)
            response["Content-Disposition"] = "attachment;filename=%s.%s" % (file_name.split('/')[1], file_extension)
            return response
        
        file.closed
        
class TaskAdvanceAdd(LoginRequiredMixin, CreateView):
    model = TaskAdvance
    template_name = "programs/advance/advance_add.html"
    login_url = LOGIN_URL
    fields = ['commentary', 'advance_file', 'percentage', 'completed' ]

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['task'] = SubProgramTask.objects.get(pk=self.kwargs['task'])
        advances = TaskAdvance.objects.filter(task=data['task'])
        data['task'].acumulate_percentage = sum(advance.percentage for advance in advances)
        return data

    def form_valid(self, form):
        form.instance.task = SubProgramTask.objects.get(pk=self.kwargs['task'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('subprogramtask_detail', kwargs={'pk': self.kwargs['task']})

templates/programs/advance/advance_add.html
{% extends 'base_home.html'%}
{% block title %} Registar Avance {% endblock %}

{% load static %}

{% block extra_head %} 
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
<meta name="description" content="bootstrap admin template">
<meta name="author" content="">

<!-- Stylesheets -->
<link rel="stylesheet" href="{% static 'unal/global/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'unal/global/css/bootstrap-extend.min.css' %}">
<link rel="stylesheet" href="{% static 'unal/assets/css/site.min.css' %}">

<!-- Plugins -->
<link rel="stylesheet" href="{% static 'unal/global/vendor/animsition/animsition.css' %}">
<link rel="stylesheet" href="{% static 'unal/global/vendor/dropify/dropify.min.css' %}">
<!-- Fonts -->
<link rel="stylesheet" href="{% static 'unal/global/fonts/web-icons/web-icons.min.css' %}">
<link rel="stylesheet" href="{% static 'unal/global/fonts/brand-icons/brand-icons.min.css' %}">
<link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>

<!-- Scripts -->
<script src="{% static 'unal/global/vendor/breakpoints/breakpoints.js' %}"></script>
<script>
  Breakpoints();
</script>
{% endblock %}

{% block class_doby %}class="animsition app-contacts page-aside-left"{% endblock %}

{% block content %}

<nav class="site-navbar navbar navbar-default navbar-fixed-top navbar-mega" role="navigation">

  {% include "header.html" %}

  <div class="navbar-container container-fluid">
    <!-- Navbar Collapse -->
    {% include "navbar.html" %}
    <!-- End Navbar Collapse -->

    <!-- Site Navbar Seach -->
    <div class="collapse navbar-search-overlap" id="site-navbar-search">
      <form role="search">
        <div class="form-group">
          <div class="input-search">
            <i class="input-search-icon wb-search" aria-hidden="true"></i>
            <input type="text" class="form-control" name="site-search" placeholder="Search...">
            <button type="button" class="input-search-close icon wb-close" data-target="#site-navbar-search"
              data-toggle="collapse" aria-label="Close"></button>
          </div>
        </div>
      </form>
    </div>
    <!-- End Site Navbar Seach -->
  </div>
</nav>
{% include "menu.html" %}

<div class="page bg-white">
    <div class="page-main">

        <!--Header-->
        <div class="page-header">
            <h1 class="page-title">Registrar Nuevo Avance</h1>
            <div class="page-header-actions"> 
                <button title="Voler a lista de programas" class="btn btn-outline-primary btn-sm" type="button"
                    onclick="location.href='{% url 'subprogramtask_detail' pk=task.pk %}'">
                    <i class="icon wb-arrow-left" aria-hidden="true"></i>Volver
                </button>
            </div>
        </div>

        <!--Body-->
        <div class="page-content">
            <div class="row col-12">
                <div class="col-8">
                    <!--Form-->
                    <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                        <!--File-->
                        <div class="form-group">
                            <h4 class="example-title">Avance:</h4>
                            <input type="file" name="advance_file"/>
                        </div>
                        <!--Comentary-->
                        <div class="form-group">
                            <h4 class="example-title">Comentario:</h4>
                            <textarea class="form-control" rows="3" name="commentary" required placeholder="Escriba un comentario referente al avance"></textarea>
                        </div>
                        <small id="passwordHelpBlock" class="form-text text-muted">
                            <strong>El porcentaje que se registra no debe superar el 100% del total de la tarea.</strong>
                        </small>
                        <!--Percentage-->
                        <div class="form-group">
                            <h4 for="id_percentage" class="example-title">Porcentaje del avance:</h4>
                            <div class="col-12">
                                <div class="input-group mb-3">
                                    <input class="form-control" name="percentage" id="id_percentage" max="30"
                                        placeholder="Escribe el número correspondiente al porcentaje de avance: 10, 30, 70, etc." required="">
                                    <div class="input-group-append">
                                        <span class="input-group-text" id="basic-addon2">%</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        Avance total de la tarea:
                        <div class="progress">
                            <div class="progress-bar" role="progressbar" style="width: {{ task.acumulate_percentage }}%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100">{{ task.acumulate_percentage }}%</div>
                            <div class="progress-bar progress-bar-striped bg-success" id="new_progress" role="progressbar" style="width: 0%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <!--Btn guardar-->
                        <div class="text-center">
                            <button type="submit" class="btn btn-success col-md-2">Registrar</button>
                        </div>
                    </form>
                </div>
                <!--Program info-->
                <div class="col-4">
                    <div class="panel" style="border: 1px solid #94b43b;">
                        <div class="panel-heading" style="border-bottom: 1px solid #94b43b; background-color: #94b43b;">
                            <h4 class="panel-title">Información de la tarea</h4>
                        </div>
                        <div class="panel-body">
                            <br>
                            <h5>Nombre de la tarea</h5>{{ task.name }}
                            <h5>Descripción de la tarea</h5>{{ task.commentary }}
                            <h5>Porcentaje completado</h5>{{ task.acumulate_percentage }}%
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include "footer.html" %}
<!-- Core  -->
<script src="{% static 'unal/global/vendor/babel-external-helpers/babel-external-helpers.js' %}"></script>
<script src="{% static 'unal/global/vendor/jquery/jquery.js' %}"></script>
<script src="{% static 'unal/global/vendor/popper-js/umd/popper.min.js' %}"></script>
<script src="{% static 'unal/global/vendor/bootstrap/bootstrap.js' %}"></script>
<script src="{% static 'unal/global/vendor/animsition/animsition.js' %}"></script>
<script src="{% static 'unal/global/vendor/asscrollbar/jquery-asScrollbar.js' %}"></script>
<script src="{% static 'unal/global/vendor/asscrollable/jquery-asScrollable.js' %}"></script>
<script src="{% static 'unal/global/vendor/ashoverscroll/jquery-asHoverScroll.js' %}"></script>

<!-- Scripts -->
<script src="{% static 'unal/global/js/Component.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin.js' %}"></script>
<script src="{% static 'unal/global/js/Base.js' %}"></script>
<script src="{% static 'unal/global/js/Config.js' %}"></script>

<script src="{% static 'unal/assets/js/Section/Menubar.js' %}"></script>
<script src="{% static 'unal/assets/js/Section/GridMenu.js' %}"></script>
<script src="{% static 'unal/assets/js/Section/Sidebar.js' %}"></script>
<script src="{% static 'unal/assets/js/Plugin/menu.js' %}"></script>

<!-- Page -->
<script src="{% static 'unal/assets/js/Site.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/slidepanel.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/dropify.js' %}"></script>

<script src="{% static 'unal/assets/js/BaseApp.js' %}"></script>
<script src="{% static 'unal/assets/js/App/Contacts.js' %}"></script>

<script src="{% static 'unal/assets/examples/js/apps/contacts.js' %}"></script>

<script>
// código de: https://jsfiddle.net/emkey08/tvx5e7q3, tomado de https://stackoverflow.com/questions/891696/jquery-what-is-the-best-way-to-restrict-number-only-input-for-textboxes-all?answertab=votes#tab-top
(function($) {
  $.fn.inputFilter = function(inputFilter) {
    return this.on("input keydown keyup mousedown mouseup select contextmenu drop", function() {
      if (inputFilter(this.value)) {
        this.oldValue = this.value;
        this.oldSelectionStart = this.selectionStart;
        this.oldSelectionEnd = this.selectionEnd;
      } else if (this.hasOwnProperty("oldValue")) {
        this.value = this.oldValue;
        this.setSelectionRange(this.oldSelectionStart, this.oldSelectionEnd);
      }
    });
  };
}(jQuery));


$(this.document).ready(function() {
    var max = 100 - "{{ task.acumulate_percentage }}"; // Porcentaje máximo del avance
        console.log(max);
    $("#id_percentage").inputFilter(function(value) {
        return /^\d*$/.test(value) && (value === "" || parseInt(value) <= max); 
    });
});

$("#id_percentage").bind('keyup mouseup', function () {
    progress_bar = $('#new_progress');
    progress_bar.css({width: this.value+"%"});
    progress_bar.empty();
    progress_bar.append(this.value+'%');
});
</script>
{% endblock content %}

templates/programs/advance/advance_by_task.html
{% for advance in  advances %}
<div class="col-3 card card-shadow">
    <div class="card-img-top cover overlay overlay-hover">
        <div class="text-center">
            <i class="cover-image overlay-figure overlay-scale icon wb-folder" aria-hidden="true" style="font-size: 64px;"></i>            
        </div>
    </div>
    <div class="card-block">
        <h3 class="card-title">Avance Nº {{ forloop.counter }}</h3>
        <p class="card-text">
            <span class="badge badge-round badge-primary float-right">{{ advance.upload_date }}</span>
        </p>
        <br>
        <p class="card-text">{{ advance.commentary }}</p>
        <p class="card-text">Porcentaje de la tarea: {{ advance.percentage }}%</p>
    </div>
    <div class="card-block clearfix text-center">
        <a class="btn btn-outline btn-info card-link" href="{% url 'task_advance_download' document_path=advance.advance_file %}">Descargar</a>
        <div class="card-actions float-right"></div>
    </div>
</div>
{% endfor %}