academic/urls.py
from django.urls import path
from django.conf.urls import url, include

from academic.views import *


from . import views

urlpatterns = [
    path('', views.index, name='academic'),
    # Thesis
    path('thesis/', Thesis.as_view(), name='thesis_list'),
    path('thesis/new/', Thesis.register, name='thesis_new'),

    path('thesis/<int:pk>/', ThesisDetail.as_view(), name='thesis_detail'),
    path('thesis/update/<int:pk>/', ThesisUpdate.as_view(), name='thesis_update'),
    path('thesis/delete/<int:pk>/', ThesisDelete.as_view(), name='thesis_delete'),
    
    ## Comments
    path('thesis/add_comment/<int:thesis_pk>', ComentThesis.register, name='comment_thesis_new'),
    path('thesis/upload_document/<int:thesis_pk>', Thesis.upload_document, name='upload_thesis_document'),
    path('thesis/documents_list/<int:thesis_pk>', Thesis.documents_list, name='thesis_documents_list'),
    path('thesis/document_viewer/<path:document_path>', Thesis.document_viewer, name='thesis_document_viewer'),
    # Advance
    path('advance/', AdvanceList.as_view(), name='advance_list'),
    path('advance/modal/<int:thesis>', Advance.register_modal, name='advance_modal'),
    path('advance/new/', Advance.register, name='advance_new'),
    path('advance/thesis/<int:thesis>', Advance.advance_by_thesis, name='advance_list'),

    #Student
    path('student/', Student.as_view(), name='student_list'),
    path('student/new/', Student.register, name='student_new'),
    path('student/edit/<int:user>/', Student.edit, name='student_edit'),
    path('student/disable/', Student.disabledStudent, name='student_disable'),
    path('student/update_password/<int:user>', Student.update_password, name='student_update_password'),

    #Teacher
    path('teacher/', TeacherView.as_view(), name='teacher_list'),
    path('teacher/new/', TeacherView.register, name='teacher_new'),
    path('teacher/edit/<int:user>/', TeacherView.edit, name='teacher_edit'),
    path('teacher/disable/', TeacherDisable.disabledTeacher, name='teacher_disable'),
    path('teacher/update_password/<int:user>', TeacherView.update_password, name='teacher_update_password'),

    #Excel
    path('export_excel/<str:data>', export, name='export_to_excel'),
]

home/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views


urlpatterns = [
    path('', views.home, name='home'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from django.conf import settings
from django.conf.urls.static import static

from users.views import login

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    # path('accounts/', include('accounts.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),

    # users
    path('', include('users.urls')),
    # home
    path('home', include('home.urls')),
    # academic
    path('academic/', include('academic.urls')),
    #programs
    path('programs/', include('programs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

academic/models.py
from users.models import CustomUser
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from rolepermissions.roles import assign_role


class CivilState(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Gender(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Nationality(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=100)
    origin_country = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class HealthInformation(models.Model):
    grupo_sanguineo = models.CharField(max_length=3)
    rh = models.CharField(max_length=1)
    eps = models.CharField(max_length=30)

# class Rol(models.Model):
#     name = models.CharField(max_length=50)
#     description = models.CharField(max_length=100)

#     def __str__(self):
#         return self.name


class PersonalInformation(models.Model):
    gender = models.ForeignKey(Gender, on_delete=models.CASCADE)
    birth_date = models.DateField(null=True, blank=True)
    civil_state = models.ForeignKey(CivilState, on_delete=models.CASCADE)
    nationality = models.ForeignKey(Nationality, on_delete=models.CASCADE)
    address = models.CharField(max_length=200, null=True, blank=True)
    mobile = models.CharField(max_length=10)
    health_information = models.OneToOneField(
        HealthInformation, on_delete=models.CASCADE)
    photo = models.ImageField(
        upload_to="thesis_photos", max_length=100, blank=True, null=True)


class InstitutionalInformation(models.Model):
    # rol = models.ForeignKey(Rol, on_delete=models.CASCADE)
    cvlac = models.CharField(max_length=200)
    institutional_email = models.EmailField(
        'institutional email', null=False, blank=False, unique=True, default="default_email@unal.edu.co")


class Student(models.Model):
    user = models.OneToOneField(
        CustomUser, on_delete=models.CASCADE, unique=True)
    personal_information = models.OneToOneField(
        PersonalInformation, null=False, on_delete=models.CASCADE, default=-1)
    institutional_information = models.ForeignKey(
        InstitutionalInformation, null=False, on_delete=models.CASCADE, default=-1)
    objects = models.Manager()

    def __str__(self):
        return self.user.first_name+" "+self.user.last_name
# Teacher model


class Teacher(models.Model):
    user = models.OneToOneField(
        CustomUser, on_delete=models.CASCADE, unique=True)
    personal_information = models.OneToOneField(
        PersonalInformation, null=False, on_delete=models.CASCADE)
    institutional_information = models.ForeignKey(
        InstitutionalInformation, null=False, on_delete=models.CASCADE)
    objects = models.Manager()

    def __str__(self):
        return self.user.first_name+" "+self.user.last_name


class InvestigationLine(models.Model):
    name = models.CharField("name", max_length=50)
    description = models.CharField("description", max_length=250)

    def __str__(self):
        return self.name


class ThesisState(models.Model):
    name = models.CharField("name", max_length=50)
    description = models.CharField("description", max_length=250)


class Thesis(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=1024*2)
    director = models.ForeignKey(
        Teacher, related_name='teacher_director', on_delete=models.CASCADE, null=False)
    co_director = models.ForeignKey(
        Teacher, related_name='teacher_co_director', on_delete=models.CASCADE, null=False)
    investigation_line = models.ForeignKey(
        InvestigationLine, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=False)
    # para workflow
    state = models.ForeignKey(
        ThesisState, on_delete=models.CASCADE, null=False)
    publication_date = models.DateTimeField('date publicated')
    acumulate_percentage = 0


class CommentsThread(models.Model):
    comment = models.CharField("comment", max_length=200)
    submit_date = models.DateTimeField("submit_date", auto_now_add=True)
    author = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, null=False)
    thesis = models.ForeignKey(Thesis, on_delete=models.CASCADE, null=False)


class Document(models.Model):
    document_file = models.FileField(
        "file", upload_to="thesis_documents", max_length=100)
    title = models.CharField("title", max_length=50)
    description = models.CharField("description", max_length=250)
    thesis = models.ForeignKey(Thesis, on_delete=models.CASCADE, null=False)


class Advance(models.Model):
    thesis = models.ForeignKey(Thesis, on_delete=models.CASCADE)
    description = models.TextField(max_length=1024*2)
    percentage = models.IntegerField()
    period = models.CharField(max_length=200)         # periodo
    observation = models.TextField(max_length=1024*2)
    # Porcentajes por revisar
    # porcentage_proposed = models.CharField(max_length=200)
    # porcentage_execute = models.CharField(max_length=200)
    # state = models.CharField(max_length=2)                   # para workflow
    creation_date = models.DateTimeField("creation date", auto_now_add=True)


class Period(models.Model):
    year = models.CharField(max_length=4)
    tremester = models.CharField(max_length=2)
    active = models.BooleanField()

    def __str__(self):
        return self.year+"-"+self.tremester

academic/forms.py
from users.models import CustomUser
from django.db import transaction
from django import forms
from .models import Student, Gender, Nationality, CivilState, Thesis, Teacher, InvestigationLine, Advance, CommentsThread, Document, Period

class StudentCreationForm(forms.ModelForm):
    gender = forms.ModelChoiceField(queryset=Gender.objects.all(), initial={'field1': Gender.pk},
                       widget=forms.Select(attrs={'class':'form-control', 'id':'id_gender'})
                    )

    nationality = forms.ModelChoiceField(queryset=Nationality.objects.all(), initial={'field1': Nationality.pk},
                       widget=forms.Select(attrs={'class':'form-control', 'id':'id_nationality'})
                    )

    civil_state = forms.ModelChoiceField(queryset=CivilState.objects.all(), initial={'field1': CivilState.pk},
                       widget=forms.Select(attrs={'class':'form-control', 'id':'id_civilState'})
                    )

    photo = forms.ImageField(widget=forms.FileInput(attrs={'class': 'custom-file-input', 'id': 'id_photo'}), required=False)
    
    def __init__(self, *args, **kwargs):
        super(StudentCreationForm, self).__init__(*args, **kwargs)
        try:
            self.fields['gender'].initial = self.instance.personal_information.gender.pk
            self.fields['nationality'].initial = self.instance.personal_information.nationality.pk
            self.fields['civil_state'].initial = self.instance.personal_information.civil_state.pk
            self.fields['photo'].initial = self.instance.personal_information.photo
        except:
            None

    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'email','gender', 'nationality', 'civil_state')

class TeacherCreationForm(forms.ModelForm):
    gender = forms.ModelChoiceField(queryset=Gender.objects.all(), initial={'field1': Gender.pk},
                       widget=forms.Select(attrs={'class':'form-control', 'id':'id_gender'})
                    )

    nationality = forms.ModelChoiceField(queryset=Nationality.objects.all(), initial={'field1': Nationality.pk},
                       widget=forms.Select(attrs={'class':'form-control', 'id':'id_nationality'})
                    )
    
    civil_state = forms.ModelChoiceField(queryset=CivilState.objects.all(), initial={'field1': CivilState.pk},
                       widget=forms.Select(attrs={'class':'form-control', 'id':'id_civilState'})
                    )

    photo = forms.ImageField(widget=forms.FileInput(attrs={'class': 'custom-file-input'}), required=False)

    def __init__(self, *args, **kwargs):
        super(TeacherCreationForm, self).__init__(*args, **kwargs)
        try:
            self.fields['gender'].initial = self.instance.personal_information.gender.pk
            self.fields['nationality'].initial = self.instance.personal_information.nationality.pk
            self.fields['civil_state'].initial = self.instance.personal_information.civil_state.pk
            self.fields['photo'].initial = self.instance.personal_information.photo
        except:
            None
    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'email', 'gender', 'nationality', 'civil_state')

class ThesisCreationForm(forms.ModelForm):
    director = forms.ModelChoiceField(queryset=Teacher.objects.all(), initial={'field1': Teacher.pk},
                       widget=forms.Select(attrs={'class':'form-control selector', 'id':'id_director'})
                    )

    student = forms.ModelChoiceField(queryset=Student.objects.all(), initial={'field1': Student.pk},
                       widget=forms.Select(attrs={'class':'form-control selector', 'id':'id_student'})
                    )
    co_director = forms.ModelChoiceField(queryset=Teacher.objects.all(), initial={'field1': Teacher.pk},
                       widget=forms.Select(attrs={'class':'form-control selector', 'id':'id_co_director'})
                    )
    investigation_line = forms.ModelChoiceField(queryset=InvestigationLine.objects.all(), initial={'field1': InvestigationLine.pk},
                        widget=forms.Select(attrs={'class':'form-control selector', 'id':'id_investigation_line'})
                    ) 
    class Meta:
        model = Thesis
        fields = ('name', 'description', "director", "co_director", "investigation_line", "student", "publication_date")
    

class AdvanceCreationForm(forms.ModelForm):
    period = forms.ModelChoiceField(queryset=Period.objects.filter(active=True), initial={'field1': Period.pk},
                        widget=forms.Select(attrs={'class':'form-control selector', 'id':'id_period'})
                    ) 
    class Meta:
        model = Advance
        fields = ("thesis","description", "percentage", "period", "observation")
    
    def __init__(self, *args, **kwargs):
        super(AdvanceCreationForm, self).__init__(*args, **kwargs)

class CommentaryThesisForm(forms.ModelForm):
    class Meta:
        model = CommentsThread
        fields = ("comment",)

class DocumentForm(forms.ModelForm):
    document_file = forms.FileField(required=True)
    
    class Meta:
        model = Document
        fields = ("document_file", "title", "description")

templates/academic/thesis_confirm_delete.html
<form method="post">{% csrf_token %}
    ¿Estás seguro que deseas borrar el curso "{{ object }}"?
    <input type="submit" value="Submit" />
</form>

templates/academic/thesis_detail.html
<h1>{{ thesis.name }}</h1>
<p>Fecha de inicio: <i>{{ thesis.direct }}</i></p>
<p>Fecha de fin: <i>{{ thesis.student }}</i></p>
<p>
    <a href="{% url 'thesis_list' %}">Regresar</a>
</p>

templates/academic/thesis_form.html
{% extends 'base_home.html' %}

{% block title %}Crear Tesis{% endblock %}

{% load static %}

{% block extra_head %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
<meta name="description" content="bootstrap admin template">
<meta name="author" content="">

<link rel="apple-touch-icon" href="{% static 'unal/assets/images/apple-touch-icon.png' %}">
<link rel="shortcut icon" href="{% static 'unal/assets/images/favicon.ico' %}">

<!-- Stylesheets -->
<link rel="stylesheet" href="{% static 'unal/global/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'unal/global/css/bootstrap-extend.min.css' %}">
<link rel="stylesheet" href="{% static 'unal/assets/css/site.min.css' %}">
<link rel="stylesheet" href="{% static 'unal/assets/css/styles.css' %}">
<!--new in thesis list-->


<!-- Plugins -->
<link rel="stylesheet" href="{% static 'unal/global/vendor/animsition/animsition.css' %}">
<link rel="stylesheet" href="{% static 'unal/global/vendor/asscrollable/asScrollable.css' %}">
<link rel="stylesheet" href="{% static 'unal/global/vendor/switchery/switchery.css' %}">
<link rel="stylesheet" href="{% static 'unal/global/vendor/intro-js/introjs.css' %}">
<link rel="stylesheet" href="{% static 'unal/global/vendor/slidepanel/slidePanel.css' %}">
<link rel="stylesheet" href="{% static 'unal/global/vendor/flag-icon-css/flag-icon.css' %}">
<link rel="stylesheet" href="{% static 'unal/assets/examples/css/apps/contacts.css' %}">
<link rel="stylesheet" href="{% static 'unal/global/vendor/tablesaw/tablesaw.css' %}">


<!-- Fonts -->
<link rel="stylesheet" href="{% static 'unal/global/fonts/web-icons/web-icons.min.css' %}">
<link rel="stylesheet" href="{% static 'unal/global/fonts/brand-icons/brand-icons.min.css' %}">
<link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>

<!--[if lt IE 9]>
  <script src="{% static 'unal/global/vendor/html5shiv/html5shiv.min.js' %}"></script>
  <![endif]-->

<!--[if lt IE 10]>
  <script src="{% static 'unal/global/vendor/media-match/media.match.min.js' %}"></script>
  <script src="{% static 'unal/global/vendor/respond/respond.min.js' %}"></script>
  <![endif]-->

<!-- Scripts -->
<script src="{% static 'unal/global/vendor/breakpoints/breakpoints.js' %}"></script>
<script>
    Breakpoints();
</script>

<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/css/select2.min.css" rel="stylesheet" />

{% endblock %}

{% block class_doby %}class="animsition app-contacts page-aside-left"{% endblock %}

{% block content %}

<!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

<nav class="site-navbar navbar navbar-default navbar-fixed-top navbar-mega" role="navigation">

    {% include "header.html" %}

    <div class="navbar-container container-fluid">
        <!-- Navbar Collapse -->
        {% include "navbar.html" %}
        <!-- End Navbar Collapse -->

        <!-- Site Navbar Seach -->
        <div class="collapse navbar-search-overlap" id="site-navbar-search">
            <form role="search">
                <div class="form-group">
                    <div class="input-search">
                        <i class="input-search-icon wb-search" aria-hidden="true"></i>
                        <input type="text" class="form-control" name="site-search" placeholder="Search...">
                        <button type="button" class="input-search-close icon wb-close" data-target="#site-navbar-search"
                            data-toggle="collapse" aria-label="Close"></button>
                    </div>
                </div>
            </form>
        </div>
        <!-- End Site Navbar Seach -->
    </div>
</nav>
{% include "menu.html" %}

<!-- Page -->

<div class="page bg-white">

    <!-- Contacts Content -->
    <div class="page-main">

        <!-- Contacts Content Header -->
        <div class="page-header">
            {% include 'academic/thesis/return_button.html' %}
            <h1 class="page-title">Registrar Nueva Tesis</h1>
            <div class="page-header-actions">
            </div>
        </div>

        <!-- Contacts Content -->
        <div id="contactsContent" class="page-content page-content-table" data-plugin="selectable">

            <form method="post">
                {% csrf_token %}
                {{ form.errors }}
                <div class="form-group ">
                    <div class="col-sm-7">
                        <label for="id_name" class="col-sm-6 col-form-label">Nombre de la tesis: </label>
                        <input type="text" class="form-control" name="name" maxlength="150" id="id_name"
                            placeholder="Nombre de la tesis">
                    </div>
                </div>
                <div class="form-group ">
                    <div class="col-sm-7">
                        <label for="id_description" class="col-sm-6 col-form-label">Descripción: </label>
                        <textarea name="description" class="form-control"
                            placeholder="Ingrese la descripcion de la tesis" id="id_description" cols="35"
                            rows="6"></textarea>
                    </div>
                </div>
                <!--<div class="form-group form-inline">
                    <div class="col-sm-8">
                        <label for="id_periodo" class="col-sm-1 col-form-label">Periodo: </label>
                        <input type="text" class="form-control" name="periodo" maxlength="10" required=""
                            id="id_periodo" placeholder="Periodo">
                        <button class="btn btn-primary" type="button">Buscar</button>
                    </div>
                </div>-->
                <div class="form-group ">
                    <div class="col-sm-7">
                        <label for="id_director" class="col-sm-6 col-form-label">Director: </label>
                        <!--<input type="text" class="form-control" name="director" maxlength="254" required=""
                            id="id_director" placeholder="Director del proyecto">-->
                        {{ form.director }}
                    </div>
                </div>
                <div class="form-group ">
                    <div class="col-sm-7">
                        <label for="id_co_director" class="col-sm-6 col-form-label">Co-Director: </label>
                        <!--<input type="text" class="form-control" name="director" maxlength="254" required=""
                            id="id_director" placeholder="Director del proyecto">-->
                        {{ form.co_director }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-7">
                        <label for="id_student" class="col-sm-6 col-form-label">Estudiante: </label>
                        {% comment %} <input type="text" class="form-control" name="student" maxlength="200" required=""
                            id="id_student" placeholder="Nombre del estudiante"> {% endcomment %}
                        {{ form.student }}
                    </div>
                </div>
                <!--<div class="form-group ">
                    <div class="col-sm-7">
                        <label for="id_porcentage" class="col-sm-6 col-form-label">Porcentaje: </label>
                        <input type="text" class="form-control" name="porcentage" maxlength="200" required=""
                            id="id_porcentage" placeholder="Porcentaje de la tesis">
                    </div>
                </div>-->
                <!--<div class="form-group ">
                    <div class="col-sm-7">
                        <label for="id_state" class="col-sm-6 col-form-label">Estado</label>
                        <input type="text" class="form-control" name="state" maxlength="128" required="" id="id_state"
                            placeholder="Estado de la tesis">
                    </div>
                </div>-->
                <div class="form-group ">
                    <div class="col-sm-7">
                        <label for="id_investigation_line" class="col-sm-6 col-form-label">Linea de investigación: </label>
                        <!--<input type="text" class="form-control" name="director" maxlength="254" required=""
                            id="id_director" placeholder="Director del proyecto">-->
                        {{ form.investigation_line }}
                    </div>
                </div>
                <div class="form-group ">
                    <div class="col-sm-7">
                        <label for="id_publication_date" class="col-sm-6 col-form-label">Fecha de publicación: </label>
                        <input type="date" class="form-control" required pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}"
                            name="publication_date" id="id_publication_date" placeholder="Fecha de publicación">
                    </div>
                </div>
                <div class="form-group ">
                    <div class="col-sm-7">
                        <input type="submit" class="btn btn-primary" value="Guardar" />
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>


<!-- End Page -->


<!-- Footer -->
{% include "footer.html" %}

<!-- Core  -->
<script src="{% static 'unal/global/vendor/babel-external-helpers/babel-external-helpers.js' %}"></script>
<script src="{% static 'unal/global/vendor/jquery/jquery.js' %}"></script>
<!--<script src="{% static 'node_modules/chosen/main.js' %}"></script>-->
<script src="{% static 'unal/global/vendor/popper-js/umd/popper.min.js' %}"></script>
<script src="{% static 'unal/global/vendor/bootstrap/bootstrap.js' %}"></script>
<script src="{% static 'unal/global/vendor/animsition/animsition.js' %}"></script>
<script src="{% static 'unal/global/vendor/mousewheel/jquery.mousewheel.js' %}"></script>
<script src="{% static 'unal/global/vendor/asscrollbar/jquery-asScrollbar.js' %}"></script>
<script src="{% static 'unal/global/vendor/asscrollable/jquery-asScrollable.js' %}"></script>
<script src="{% static 'unal/global/vendor/ashoverscroll/jquery-asHoverScroll.js' %}"></script>

<!-- Plugins -->
<script src="{% static 'unal/global/vendor/switchery/switchery.js' %}"></script>
<script src="{% static 'unal/global/vendor/intro-js/intro.js' %}"></script>
<script src="{% static 'unal/global/vendor/screenfull/screenfull.js' %}"></script>
<script src="{% static 'unal/global/vendor/slidepanel/jquery-slidePanel.js' %}"></script>
<script src="{% static 'unal/global/vendor/aspaginator/jquery-asPaginator.min.js' %}"></script>
<script src="{% static 'unal/global/vendor/jquery-placeholder/jquery.placeholder.js' %}"></script>
<script src="{% static 'unal/global/vendor/bootbox/bootbox.js' %}"></script>


<!-- Scripts -->
<script src="{% static 'unal/global/js/Component.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin.js' %}"></script>
<script src="{% static 'unal/global/js/Base.js' %}"></script>
<script src="{% static 'unal/global/js/Config.js' %}"></script>

<script src="{% static 'unal/assets/js/Section/Menubar.js' %}"></script>
<script src="{% static 'unal/assets/js/Section/GridMenu.js' %}"></script>
<script src="{% static 'unal/assets/js/Section/Sidebar.js' %}"></script>
<script src="{% static 'unal/assets/js/Section/PageAside.js' %}"></script>
<script src="{% static 'unal/assets/js/Plugin/menu.js' %}"></script>

<script src="{% static 'unal/global/js/config/colors.js' %}"></script>
<script src="{% static 'unal/assets/js/config/tour.js' %}"></script>
<script>Config.set('assets', "{% static 'unal/assets' %}");</script>

<!-- Page -->
<script src="{% static 'unal/assets/js/Site.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/asscrollable.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/slidepanel.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/switchery.js' %}"></script>

<script src="{% static 'unal/global/js/Plugin/sticky-header.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/action-btn.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/asselectable.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/editlist.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/aspaginator.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/animate-list.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/jquery-placeholder.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/material.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/selectable.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/bootbox.js' %}"></script>
<script src="{% static 'unal/assets/js/BaseApp.js' %}"></script>
<script src="{% static 'unal/assets/js/App/Contacts.js' %}"></script>
<script src="{% static 'unal/assets/examples/js/apps/contacts.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/js/select2.min.js"></script>

<script>
    $(document).ready(function() {
        $('.selector').select2();
    });
</script>
{% endblock %}