home/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views


urlpatterns = [
    path('', views.home, name='home'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from django.conf import settings
from django.conf.urls.static import static

from users.views import login

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    # path('accounts/', include('accounts.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),

    # users
    path('', include('users.urls')),
    # home
    path('home', include('home.urls')),
    # academic
    path('academic/', include('academic.urls')),
    #programs
    path('programs/', include('programs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

academic/models.py
from users.models import CustomUser
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from rolepermissions.roles import assign_role


class CivilState(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Gender(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Nationality(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=100)
    origin_country = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class HealthInformation(models.Model):
    grupo_sanguineo = models.CharField(max_length=3)
    rh = models.CharField(max_length=1)
    eps = models.CharField(max_length=30)

# class Rol(models.Model):
#     name = models.CharField(max_length=50)
#     description = models.CharField(max_length=100)

#     def __str__(self):
#         return self.name


class PersonalInformation(models.Model):
    gender = models.ForeignKey(Gender, on_delete=models.CASCADE)
    birth_date = models.DateField(null=True, blank=True)
    civil_state = models.ForeignKey(CivilState, on_delete=models.CASCADE)
    nationality = models.ForeignKey(Nationality, on_delete=models.CASCADE)
    address = models.CharField(max_length=200, null=True, blank=True)
    mobile = models.CharField(max_length=10)
    health_information = models.OneToOneField(
        HealthInformation, on_delete=models.CASCADE)
    photo = models.ImageField(
        upload_to="thesis_photos", max_length=100, blank=True, null=True)


class InstitutionalInformation(models.Model):
    # rol = models.ForeignKey(Rol, on_delete=models.CASCADE)
    cvlac = models.CharField(max_length=200)
    institutional_email = models.EmailField(
        'institutional email', null=False, blank=False, unique=True, default="default_email@unal.edu.co")


class Student(models.Model):
    user = models.OneToOneField(
        CustomUser, on_delete=models.CASCADE, unique=True)
    personal_information = models.OneToOneField(
        PersonalInformation, null=False, on_delete=models.CASCADE, default=-1)
    institutional_information = models.ForeignKey(
        InstitutionalInformation, null=False, on_delete=models.CASCADE, default=-1)
    objects = models.Manager()

    def __str__(self):
        return self.user.first_name+" "+self.user.last_name
# Teacher model


class Teacher(models.Model):
    user = models.OneToOneField(
        CustomUser, on_delete=models.CASCADE, unique=True)
    personal_information = models.OneToOneField(
        PersonalInformation, null=False, on_delete=models.CASCADE)
    institutional_information = models.ForeignKey(
        InstitutionalInformation, null=False, on_delete=models.CASCADE)
    objects = models.Manager()

    def __str__(self):
        return self.user.first_name+" "+self.user.last_name


class InvestigationLine(models.Model):
    name = models.CharField("name", max_length=50)
    description = models.CharField("description", max_length=250)

    def __str__(self):
        return self.name


class ThesisState(models.Model):
    name = models.CharField("name", max_length=50)
    description = models.CharField("description", max_length=250)


class Thesis(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=1024*2)
    director = models.ForeignKey(
        Teacher, related_name='teacher_director', on_delete=models.CASCADE, null=False)
    co_director = models.ForeignKey(
        Teacher, related_name='teacher_co_director', on_delete=models.CASCADE, null=False)
    investigation_line = models.ForeignKey(
        InvestigationLine, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=False)
    # para workflow
    state = models.ForeignKey(
        ThesisState, on_delete=models.CASCADE, null=False)
    publication_date = models.DateTimeField('date publicated')
    acumulate_percentage = 0


class CommentsThread(models.Model):
    comment = models.CharField("comment", max_length=200)
    submit_date = models.DateTimeField("submit_date", auto_now_add=True)
    author = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, null=False)
    thesis = models.ForeignKey(Thesis, on_delete=models.CASCADE, null=False)


class Document(models.Model):
    document_file = models.FileField(
        "file", upload_to="thesis_documents", max_length=100)
    title = models.CharField("title", max_length=50)
    description = models.CharField("description", max_length=250)
    thesis = models.ForeignKey(Thesis, on_delete=models.CASCADE, null=False)


class Advance(models.Model):
    thesis = models.ForeignKey(Thesis, on_delete=models.CASCADE)
    description = models.TextField(max_length=1024*2)
    percentage = models.IntegerField()
    period = models.CharField(max_length=200)         # periodo
    observation = models.TextField(max_length=1024*2)
    # Porcentajes por revisar
    # porcentage_proposed = models.CharField(max_length=200)
    # porcentage_execute = models.CharField(max_length=200)
    # state = models.CharField(max_length=2)                   # para workflow
    creation_date = models.DateTimeField("creation date", auto_now_add=True)


class Period(models.Model):
    year = models.CharField(max_length=4)
    tremester = models.CharField(max_length=2)
    active = models.BooleanField()

    def __str__(self):
        return self.year+"-"+self.tremester

home/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _

from .managers import CustomUserManager


class CustomUser(AbstractUser):
    username = models.CharField(max_length=50, default="default_username", unique=True)
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        self.username = self.email.split('@')[0]
        super(CustomUser, self).save(*args, **kwargs)

home/views.py
from django.shortcuts import render, redirect

# Create your views here.
def home(request):
    if request.user.is_authenticated:
        return render(request, "home.html")
    
    return redirect("login")

templates/base.html
<!DOCTYPE html>
<html class="no-js css-menubar" lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
  <meta name="description" content="bootstrap admin template">
  <meta name="author" content="">

  <link rel="apple-touch-icon" href="{% static 'unal/assets/images/apple-touch-icon.png' %}">
  <link rel="shortcut icon" href="{% static 'unal/assets/images/favicon.ico' %}">

  <!-- Stylesheets -->
  <link rel="stylesheet" href="{% static 'unal/global/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'unal/global/css/bootstrap-extend.min.css' %}">
  <link rel="stylesheet" href="{% static 'unal/assets/css/site.min.css' %}">

  <!-- Plugins -->
  <link rel="stylesheet" href="{% static 'unal/global/vendor/animsition/animsition.css' %}">
  <link rel="stylesheet" href="{% static 'unal/global/vendor/asscrollable/asScrollable.css' %}">
  <link rel="stylesheet" href="{% static 'unal/global/vendor/switchery/switchery.css' %}">
  <link rel="stylesheet" href="{% static 'unal/global/vendor/intro-js/introjs.css' %}">
  <link rel="stylesheet" href="{% static 'unal/global/vendor/slidepanel/slidePanel.css' %}">
  <link rel="stylesheet" href="{% static 'unal/global/vendor/flag-icon-css/flag-icon.css' %}">
  <link rel="stylesheet" href="{% static 'unal/assets/examples/css/pages/login-v2.css' %}">

  <!-- Fonts -->
  <link rel="stylesheet" href="{% static 'unal/global/fonts/web-icons/web-icons.min.css' %}">
  <link rel="stylesheet" href="{% static 'unal/global/fonts/brand-icons/brand-icons.min.css' %}">
  <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>

  <!--[if lt IE 9]>
    <script src="../../global/vendor/html5shiv/html5shiv.min.js"></script>
    <![endif]-->

  <!--[if lt IE 10]>
    <script src="../../global/vendor/media-match/media.match.min.js"></script>
    <script src="../../global/vendor/respond/respond.min.js"></script>
    <![endif]-->

  <!-- Scripts -->
  <script src="{% static 'unal/global/vendor/breakpoints/breakpoints.js' %}"></script>
  <script>
    Breakpoints();
  </script>

  <title>{% block title %}SIGEYPM{% endblock %}</title>

</head>

<body class="animsition page-login-v2 layout-full page-dark">
    {% block content %}
    {% endblock %}
</body>

</html>

templates/base_home.html
{% load static %}

<!DOCTYPE html>
<html class="no-js css-menubar" lang="en">

<head>
  {% block extra_head %}{% endblock %}
  <title>{% block title %}Trabajos de Grado{% endblock %}</title>
</head>

<body  {% block class_doby %}{% endblock %} >
  {% if  request.user.is_authenticated%}
    {% block content %}{% endblock %}
  {% else %}
    {% url 'login' %}
  {% endif %}
</body>

</html>

templates/base_login.html
<!DOCTYPE html>
<html class="no-js css-menubar" lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
  <meta name="description" content="bootstrap admin template">
  <meta name="author" content="">

  <link rel="apple-touch-icon" href="{% static 'unal/assets/images/apple-touch-icon.png' %}">
  <link rel="shortcut icon" href="{% static 'unal/assets/images/favicon.ico' %}">

  <!-- Stylesheets -->
  <link rel="stylesheet" href="{% static 'unal/global/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'unal/global/css/bootstrap-extend.min.css' %}">
  <link rel="stylesheet" href="{% static 'unal/assets/css/site.min.css' %}">

  <!-- Plugins -->
  <link rel="stylesheet" href="{% static 'unal/global/vendor/animsition/animsition.css' %}">
  <link rel="stylesheet" href="{% static 'unal/global/vendor/asscrollable/asScrollable.css' %}">
  <link rel="stylesheet" href="{% static 'unal/global/vendor/switchery/switchery.css' %}">
  <link rel="stylesheet" href="{% static 'unal/global/vendor/intro-js/introjs.css' %}">
  <link rel="stylesheet" href="{% static 'unal/global/vendor/slidepanel/slidePanel.css' %}">
  <link rel="stylesheet" href="{% static 'unal/global/vendor/flag-icon-css/flag-icon.css' %}">
  <link rel="stylesheet" href="{% static 'unal/assets/examples/css/pages/login-v2.css' %}">

  <!-- Fonts -->
  <link rel="stylesheet" href="{% static 'unal/global/fonts/web-icons/web-icons.min.css' %}">
  <link rel="stylesheet" href="{% static 'unal/global/fonts/brand-icons/brand-icons.min.css' %}">
  <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>

  <!--[if lt IE 9]>
    <script src="../../global/vendor/html5shiv/html5shiv.min.js"></script>
    <![endif]-->

  <!--[if lt IE 10]>
    <script src="../../global/vendor/media-match/media.match.min.js"></script>
    <script src="../../global/vendor/respond/respond.min.js"></script>
    <![endif]-->

  <!-- Scripts -->
  <script src="{% static 'unal/global/vendor/breakpoints/breakpoints.js' %}"></script>
  <script>
    Breakpoints();
  </script>

  <title>{% block title %}Trabajos de Grado{% endblock %}</title>

</head>

<body class="animsition page-login-v2 layout-full page-dark">
    {% block content %}
  <div class="input-group mb-3 justify-content-center">
    <form method="post">
    {% comment %} {{ form.as_p }} {% endcomment %}
    {% csrf_token %}
      <div class="form-group">
        <label for="username">Usuario:</label>
        <input type="text" class="form-control" id="username" aria-describedby="usernameHelp" placeholder="Nombre de usuario" name="username">
      </div>
      <div class="form-group">
        <label for="password">Contraseña:</label>
        <input type="password" class="form-control" id="password" placeholder="Contraseña" name="password">
      </div>
      <div class="form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Recuérdame</label>
      </div>
      <button type="submit" class="btn btn-primary">Ingresar</button>
    </form>
  </div>
    {% endblock %}
</body>

</html>

templates/footer.html
<footer class="site-footer">
  <div class="site-footer-legal">© 2019 <a href="#">SIGEYPM </a></div>
  <div class="site-footer-right">
  </div>
</footer>

templates/header.html
{% load static %}
<div class="navbar-header">
  <div class="navbar-brand navbar-brand-center">
    <a href="{% url 'home' %}">
      <img class="navbar-brand-logo" src="{% static 'unal/assets/images/apple-touch-icon.png' %}" title="Remark">
      <span style="color:#fff;" class="navbar-brand-text hidden-xs-down">Trabajos de Grado</span>
    </a>
  </div>
</div>

templates/student_form.html
{% extends 'base_home.html' %}

{% block title %}Crear Estudiantes{% endblock %}

{% load static %}

{% block extra_head %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
<meta name="description" content="bootstrap admin template">
<meta name="author" content="">

<link rel="apple-touch-icon" href="{% static 'unal/assets/images/apple-touch-icon.png' %}">
<link rel="shortcut icon" href="{% static 'unal/assets/images/favicon.ico' %}">

<!-- Stylesheets -->
<link rel="stylesheet" href="{% static 'unal/global/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'unal/global/css/bootstrap-extend.min.css' %}">
<link rel="stylesheet" href="{% static 'unal/assets/css/site.min.css' %}">
<link rel="stylesheet" href="{% static 'unal/assets/css/styles.css' %}">
<!--new in thesis list-->


<!-- Plugins -->
<link rel="stylesheet" href="{% static 'unal/global/vendor/animsition/animsition.css' %}">
<link rel="stylesheet" href="{% static 'unal/global/vendor/asscrollable/asScrollable.css' %}">
<link rel="stylesheet" href="{% static 'unal/global/vendor/switchery/switchery.css' %}">
<link rel="stylesheet" href="{% static 'unal/global/vendor/intro-js/introjs.css' %}">
<link rel="stylesheet" href="{% static 'unal/global/vendor/slidepanel/slidePanel.css' %}">
<link rel="stylesheet" href="{% static 'unal/global/vendor/flag-icon-css/flag-icon.css' %}">
<link rel="stylesheet" href="{% static 'unal/assets/examples/css/apps/contacts.css' %}">
<link rel="stylesheet" href="{% static 'unal/global/vendor/tablesaw/tablesaw.css' %}">


<!-- Fonts -->
<link rel="stylesheet" href="{% static 'unal/global/fonts/web-icons/web-icons.min.css' %}">
<link rel="stylesheet" href="{% static 'unal/global/fonts/brand-icons/brand-icons.min.css' %}">
<link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>

<!--[if lt IE 9]>
  <script src="{% static 'unal/global/vendor/html5shiv/html5shiv.min.js' %}"></script>
  <![endif]-->

<!--[if lt IE 10]>
  <script src="{% static 'unal/global/vendor/media-match/media.match.min.js' %}"></script>
  <script src="{% static 'unal/global/vendor/respond/respond.min.js' %}"></script>
  <![endif]-->

<!-- Scripts -->
<script src="{% static 'unal/global/vendor/breakpoints/breakpoints.js' %}"></script>
<script>
  Breakpoints();
</script>
{% endblock %}

{% block class_doby %}class="animsition app-contacts page-aside-left"{% endblock %}

{% block content %}

<!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

<nav class="site-navbar navbar navbar-default navbar-fixed-top navbar-mega" role="navigation">

  {% include "header.html" %}

  <div class="navbar-container container-fluid">
    <!-- Navbar Collapse -->
    {% include "navbar.html" %}
    <!-- End Navbar Collapse -->

    <!-- Site Navbar Seach -->
    <div class="collapse navbar-search-overlap" id="site-navbar-search">
      <form role="search">
        <div class="form-group">
          <div class="input-search">
            <i class="input-search-icon wb-search" aria-hidden="true"></i>
            <input type="text" class="form-control" name="site-search" placeholder="Search...">
            <button type="button" class="input-search-close icon wb-close" data-target="#site-navbar-search"
              data-toggle="collapse" aria-label="Close"></button>
          </div>
        </div>
      </form>
    </div>
    <!-- End Site Navbar Seach -->
  </div>
</nav>
{% include "menu.html" %}

<!-- Page -->

<div class="page bg-white">

  <!-- Contacts Content -->
  <div class="page-main">

    <!-- Contacts Content Header -->
    <div class="page-header">
      <h1 class="page-title">Registrar Nuevo Estudiante</h1>
      <div class="page-header-actions">
      </div>
    </div>

    <!-- Contacts Content -->
    <div id="contactsContent" class="page-content page-content-table" data-plugin="selectable">

      <form method="post" enctype="multipart/form-data" runat="server">
        {% csrf_token %}
        
        {% include "academic/messages/messages.html" %}
        <label for="id_first_name" class="col-sm-2 col-form-label">Nombres Completos:</label>
        <div class="form-group ">
          <div class="col-sm-7">
            <input type="text" class="form-control" name="first_name" maxlength="30" id="id_first_name"
              placeholder="Nombres" required>
          </div>
        </div>
        <label for="id_last_name" class="col-sm-2 col-form-label">Apellidos Completos:</label>
        <div class="form-group ">
          <div class="col-sm-7">
            <input type="text" class="form-control" name="last_name" maxlength="150" id="id_last_name"
              placeholder="Apellidos" required>
          </div>
        </div>
        <!-- Genero -->
        <label for="id_gender" class="col-sm-2 col-form-label">Género:</label>
        <div class="form-group ">
          <div class="col-sm-7">
            {{ form.gender }}
          </div>
        </div>
        <!-- Estado civil -->
        <label for="id_civilState" class="col-sm-2 col-form-label">Estado civil:</label>
        <div class="form-group ">
          <div class="col-sm-7">
            {{ form.civil_state }}
          </div>
        </div>
        <!-- Estado civil -->
        <label for="id_nationality" class="col-sm-2 col-form-label">Nacionalidad:</label>
        <div class="form-group ">
          <div class="col-sm-7">
            {{ form.nationality }}
          </div>
        </div>
        <!-- Teléfono -->
        <label for="id_mobile" class="col-sm-2 col-form-label">Teléfono</label>
        <div class="form-group ">
          <div class="col-sm-7">
            <input type="text" class="form-control" name="mobile" maxlength="10" required="" id="id_mobile"
              placeholder="Teléfono" data-format="(ddd) ddd-dddd">
          </div>
        </div>
        <label for="id_email" class="col-sm-2 col-form-label">Correo institucional:</label>
        <div class="form-group ">
          <div class="col-sm-7">
            <input type="email" class="form-control" name="email" maxlength="254" required="" id="id_email"
              placeholder="Email">
          </div>
        </div>
        <label for="id_address" class="col-sm-3 col-form-label">Dirección de residencia:</label>
        <div class="form-group ">
          <div class="col-sm-7">
            <input type="text" class="form-control" name="address" maxlength="200" required="" id="id_address"
              placeholder="Dirección">
          </div>
        </div>
        <label for="birth_date" class="col-sm-2 col-form-label">Fecha de nacimiento:</label>
        <div class="form-group ">
          <div class="col-sm-7">
            <input type="date" class="form-control"required pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}" name="birth_date" id="id_birth_date"
              placeholder="Fecha de Nacimiento">
          </div>
        </div>
        <label for="id_cvlac" class="col-sm-2 col-form-label">CvLac:</label>
        <div class="form-group ">
          <div class="col-sm-7">
            <input type="text" class="form-control" name="cvlac" maxlength="200" id="id_cvlac"
              placeholder="CVLAC">
          </div>
        </div>
        <div class="form-group">
          <label for="id_photo" class="col-sm-2 col-form-label">Foto del estudiante:</label>
          <div class="col-sm-7">
            <div class="custom-file">
              <input class="custom-file-input" type="file" name="photo" accept="image/*" id="id_photo">
              <label class="custom-file-label" for="id_photo">Sube una foto</label>
            </div>
            <br><br>
            <img id="student_photo" style="width:180px; height:200px;" class="img-fluid" src="#" alt="Imagen de perfil" />
          </div>
        </div>
        <div class="form-group ">
          <label for="id_password" class="col-sm-2 col-form-label">Contraseña:</label>
          <div class="col-sm-7">
            <input type="password" class="form-control" name="password" maxlength="128" required="" id="id_password">
          </div>
        </div>
        <div class="form-group ">
          <div class="col-sm-7 text-center">
            <input type="submit" class="btn btn-primary" value="Guardar" />
          </div>
        </div>
      </form>

    </div>
  </div>
</div>


<!-- End Page -->


<!-- Footer -->
{% include "footer.html" %}

<!-- Core  -->
<script src="{% static 'unal/global/vendor/babel-external-helpers/babel-external-helpers.js' %}"></script>
<script src="{% static 'unal/global/vendor/jquery/jquery.js' %}"></script>
<script src="{% static 'unal/global/vendor/popper-js/umd/popper.min.js' %}"></script>
<script src="{% static 'unal/global/vendor/bootstrap/bootstrap.js' %}"></script>
<script src="{% static 'unal/global/vendor/animsition/animsition.js' %}"></script>
<script src="{% static 'unal/global/vendor/mousewheel/jquery.mousewheel.js' %}"></script>
<script src="{% static 'unal/global/vendor/asscrollbar/jquery-asScrollbar.js' %}"></script>
<script src="{% static 'unal/global/vendor/asscrollable/jquery-asScrollable.js' %}"></script>
<script src="{% static 'unal/global/vendor/ashoverscroll/jquery-asHoverScroll.js' %}"></script>

<!-- Plugins -->
<script src="{% static 'unal/global/vendor/switchery/switchery.js' %}"></script>
<script src="{% static 'unal/global/vendor/intro-js/intro.js' %}"></script>
<script src="{% static 'unal/global/vendor/screenfull/screenfull.js' %}"></script>
<script src="{% static 'unal/global/vendor/slidepanel/jquery-slidePanel.js' %}"></script>
<script src="{% static 'unal/global/vendor/aspaginator/jquery-asPaginator.min.js' %}"></script>
<script src="{% static 'unal/global/vendor/jquery-placeholder/jquery.placeholder.js' %}"></script>
<script src="{% static 'unal/global/vendor/bootbox/bootbox.js' %}"></script>


<!-- Scripts -->
<script src="{% static 'unal/global/js/Component.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin.js' %}"></script>
<script src="{% static 'unal/global/js/Base.js' %}"></script>
<script src="{% static 'unal/global/js/Config.js' %}"></script>

<script src="{% static 'unal/assets/js/Section/Menubar.js' %}"></script>
<script src="{% static 'unal/assets/js/Section/GridMenu.js' %}"></script>
<script src="{% static 'unal/assets/js/Section/Sidebar.js' %}"></script>
<script src="{% static 'unal/assets/js/Section/PageAside.js' %}"></script>
<script src="{% static 'unal/assets/js/Plugin/menu.js' %}"></script>

<script src="{% static 'unal/global/js/config/colors.js' %}"></script>
<script src="{% static 'unal/assets/js/config/tour.js' %}"></script>
<script>Config.set('assets', "{% static 'unal/assets' %}");</script>

<!-- Page -->
<script src="{% static 'unal/assets/js/Site.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/asscrollable.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/slidepanel.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/switchery.js' %}"></script>

<script src="{% static 'unal/global/js/Plugin/sticky-header.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/action-btn.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/asselectable.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/editlist.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/aspaginator.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/animate-list.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/jquery-placeholder.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/material.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/selectable.js' %}"></script>
<script src="{% static 'unal/global/js/Plugin/bootbox.js' %}"></script>
<script src="{% static 'unal/assets/js/BaseApp.js' %}"></script>
<script src="{% static 'unal/assets/js/App/Contacts.js' %}"></script>

<script src="{% static 'unal/assets/examples/js/apps/contacts.js' %}"></script>

<script>
  function readURL(input) {
  if (input.files && input.files[0]) {
    var reader = new FileReader();
    
    reader.onload = function(e) {
      $('#student_photo').attr('src', e.target.result);
    }
    
    reader.readAsDataURL(input.files[0]);
  }
  }

  $("#id_photo").change(function() {
    readURL(this);
  });
</script>
{% endblock %}